#!/bin/bash
draw() {
  kitten icat --stdin no --transfer-mode memory --place "${w}x${h}@${x}x${y}" "$1" </dev/null >/dev/tty
  exit 1
}

file="$1"
w="$2"
h="$3"
x="$4"
y="$5"

if [[ "$(file -Lb --mime-type "$file")" == image/* ]]; then
    draw "$file"
fi

pistol "$file"
